services:
  db:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"

    networks:
      fast-api:
        ipv4_address: 170.1.1.10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fast-api
    volumes:
      - ./app:/app  # Map the 'app' directory to '/app' inside the container
    working_dir: /app
    stdin_open: true
    environment:
      - PORT=8080
      - HOST=0.0.0.0
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    ports:
      - "1000:8080"

    networks:
      fast-api:
        ipv4_address: 170.1.1.20

    depends_on:
      - db

networks:
  fast-api:
    ipam:
      config:
        - subnet: 170.1.1.0/24
